export const routesData = [
  {
    uid: 0,
    route: '/',
    component: 'Home',
    exact: true,
    label: 'Home',
  },
  {
    uid: 1,
    route: '/button',
    component: 'Button',
    exact: true,
    label: 'Button',
  },
  {
    uid: 2,
    route: '/table',
    component: 'Table',
    exact: true,
    label: 'Table',
  },
  // {
  //   uid: 3,
  //   route: '/text-input',
  //   component: 'TextInput',
  //   exact: true,
  //   label: 'TextInput',
  // },
  // {
  //   uid: 4,
  //   route: '/field-label',
  //   component: 'FieldLabel',
  //   exact: true,
  //   label: 'FieldLabel',
  // },
  // {
  //   uid: 5,
  //   route: '/notification',
  //   component: 'Notification',
  //   exact: true,
  //   label: 'Notification',
  // },
  // {
  //   uid: 6,
  //   route: '/help-text',
  //   component: 'HelpText',
  //   exact: true,
  //   label: 'HelpText',
  // },
  // {
  //   uid: 7,
  //   route: '/validation-message',
  //   component: 'ValidationMessage',
  //   exact: true,
  //   label: 'ValidationMessage',
  // },
  // {
  //   uid: 8,
  //   route: '/typography',
  //   component: 'Typography',
  //   exact: true,
  //   label: 'Typography',
  // },
  {
    uid: 3,
    route: '/select-box',
    component: 'SelectBox',
    exact: true,
    label: 'Select',
  },
  {
    uid: 4,
    route: '/checkbox',
    component: 'Checkbox',
    exact: true,
    label: 'Checkbox',
  },
  {
    uid: 5,
    route: '/radio',
    component: 'Radio',
    exact: true,
    label: 'Radio',
  },
  {
    uid: 6,
    route: '/toggleSwitch',
    component: 'ToggleSwitch',
    exact: true,
    label: 'ToggleSwitch',
  },
  // {
  //   uid: 10,
  //   route: '/dropdown',
  //   component: 'Dropdown',
  //   exact: true,
  //   label: 'Dropdown',
  // },
  // {
  //   uid: 11,
  //   route: '/icon',
  //   component: 'Icon',
  //   exact: true,
  //   label: 'Icon',
  // },
  // {
  //   uid: 12,
  //   route: '/page-layout',
  //   component: 'PageLayout',
  //   exact: true,
  //   label: 'PageLayout',
  // },
  // {
  //   uid: 13,
  //   route: '/page-header',
  //   component: 'PageHeader',
  //   exact: true,
  //   label: 'PageHeader',
  // },
  // {
  //   uid: 13,
  //   route: '/tabs',
  //   component: 'Tabs',
  //   exact: true,
  //   label: 'Tabs',
  // },
]
