export const routesData = [
  {
    uid: 0,
    route: '/',
    component: 'Home',
    exact: true,
    label: 'Home',
  },
  {
    uid: 1,
    route: '/button',
    component: 'Button',
    exact: true,
    label: 'Button',
  },
  {
    uid: 2,
    route: '/text-input',
    component: 'TextInput',
    exact: true,
    label: 'TextInput',
  },
  {
    uid: 3,
    route: '/tag',
    component: 'Tag',
    exact: true,
    label: 'Tag',
  },
  {
    uid: 4,
    route: '/editable-tag',
    component: 'EditableTag',
    exact: true,
    label: 'EditableTag',
  },
  {
    uid: 5,
    route: '/outline-tag',
    component: 'OutlineTag',
    exact: true,
    label: 'OutlineTag',
  },
  {
    uid: 6,
    route: '/field-label',
    component: 'FieldLabel',
    exact: true,
    label: 'FieldLabel',
  },
  {
    uid: 7,
    route: '/InstructionTex',
    component: 'InstructionText',
    exact: true,
    label: 'InstructionText',
  },
  {
    uid: 5,
    route: '/select-box',
    component: 'SelectBox',
    exact: true,
    label: 'Select',
  },
  {
    uid: 6,
    route: '/checkbox',
    component: 'Checkbox',
    exact: true,
    label: 'Checkbox',
  },
  {
    uid: 7,
    route: '/radio',
    component: 'Radio',
    exact: true,
    label: 'Radio',
  },
  {
    uid: 8,
    route: '/toggleSwitch',
    component: 'ToggleSwitch',
    exact: true,
    label: 'ToggleSwitch',
  },
  {
    uid: 9,
    route: '/typography',
    component: 'Typography',
    exact: true,
    label: 'Typography',
  },
  {
    uid: 10,
    route: '/text-area',
    component: 'Textarea',
    exact: true,
    label: 'Textarea',
  },
  {
    uid: 11,
    route: '/table',
    component: 'Table',
    exact: true,
    label: 'Table',
  },
  {
    uid: 12,
    route: '/modal',
    component: 'Modal',
    exact: true,
    label: 'Modal',
  },
  {
    uid: 13,
    route: '/dropdown',
    component: 'Dropdown',
    exact: true,
    label: 'Dropdown',
  },
  {
    uid: 14,
    route: '/icon',
    component: 'Icon',
    exact: true,
    label: 'Icon',
  },
  {
    uid: 15,
    route: '/accordion',
    component: 'Accordion',
    exact: true,
    label: 'Accordion',
  },
  {
    uid: 16,
    route: '/asset-card-vertical',
    component: 'AssetCardVertical',
    exact: true,
    label: 'AssetCardVertical',
  },
  {
    uid: 17,
    route: '/carousel',
    component: 'Carousel',
    exact: true,
    label: 'Carousel',
  },
  {
    uid: 18,
    route: '/field',
    component: 'Field',
    exact: true,
    label: 'Field',
  },
  {
    uid: 19,
    route: '/search',
    component: 'Search',
    exact: true,
    label: 'Search',
  },
  
  // {
  //   uid: 3,
  //   route: '/text-input',
  //   component: 'TextInput',
  //   exact: true,
  //   label: 'TextInput',
  // },
  // {
  //   uid: 5,
  //   route: '/notification',
  //   component: 'Notification',
  //   exact: true,
  //   label: 'Notification',
  // },
  // {
  //   uid: 6,
  //   route: '/help-text',
  //   component: 'HelpText',
  //   exact: true,
  //   label: 'HelpText',
  // },
  // {
  //   uid: 7,
  //   route: '/validation-message',
  //   component: 'ValidationMessage',
  //   exact: true,
  //   label: 'ValidationMessage',
  // },
  // {
  //   uid: 8,
  //   route: '/typography',
  //   component: 'Typography',
  //   exact: true,
  //   label: 'Typography',
  // },
  // {
  //   uid: 10,
  //   route: '/dropdown',
  //   component: 'Dropdown',
  //   exact: true,
  //   label: 'Dropdown',
  // },
  // {
  //   uid: 11,
  //   route: '/icon',
  //   component: 'Icon',
  //   exact: true,
  //   label: 'Icon',
  // },
  // {
  //   uid: 12,
  //   route: '/page-layout',
  //   component: 'PageLayout',
  //   exact: true,
  //   label: 'PageLayout',
  // },
  // {
  //   uid: 13,
  //   route: '/page-header',
  //   component: 'PageHeader',
  //   exact: true,
  //   label: 'PageHeader',
  // }  
]
