export const routesData = [
  {
    uid: 0,
    route: '/',
    component: 'Home',
    exact: true,
    label: 'Home',
  },
  {
    uid: 1,
    route: '/button',
    component: 'Button',
    exact: true,
    label: 'Button',
  },
  {
    uid: 2,
    route: '/text-input',
    component: 'TextInput',
    exact: true,
    label: 'TextInput',
  },
  {
    uid: 3,
    route: '/tag',
    component: 'Tag',
    exact: true,
    label: 'Tag',
  },
  {
    uid: 4,
    route: '/editable-tag',
    component: 'EditableTag',
    exact: true,
    label: 'EditableTag',
  },
  {
    uid: 5,
    route: '/outline-tag',
    component: 'OutlineTag',
    exact: true,
    label: 'OutlineTag',
  },
  // {
  //   uid: 5,
  //   route: '/notification',
  //   component: 'Notification',
  //   exact: true,
  //   label: 'Notification',
  // },
  // {
  //   uid: 6,
  //   route: '/help-text',
  //   component: 'HelpText',
  //   exact: true,
  //   label: 'HelpText',
  // },
  // {
  //   uid: 7,
  //   route: '/validation-message',
  //   component: 'ValidationMessage',
  //   exact: true,
  //   label: 'ValidationMessage',
  // },
  // {
  //   uid: 8,
  //   route: '/typography',
  //   component: 'Typography',
  //   exact: true,
  //   label: 'Typography',
  // },
  // {
  //   uid: 9,
  //   route: '/select-box',
  //   component: 'SelectBox',
  //   exact: true,
  //   label: 'SelectBox',
  // },
  // {
  //   uid: 10,
  //   route: '/dropdown',
  //   component: 'Dropdown',
  //   exact: true,
  //   label: 'Dropdown',
  // },
  // {
  //   uid: 11,
  //   route: '/icon',
  //   component: 'Icon',
  //   exact: true,
  //   label: 'Icon',
  // },
  // {
  //   uid: 12,
  //   route: '/page-layout',
  //   component: 'PageLayout',
  //   exact: true,
  //   label: 'PageLayout',
  // },
  // {
  //   uid: 13,
  //   route: '/page-header',
  //   component: 'PageHeader',
  //   exact: true,
  //   label: 'PageHeader',
  // },
  // {
  //   uid: 13,
  //   route: '/tabs',
  //   component: 'Tabs',
  //   exact: true,
  //   label: 'Tabs',
  // },
]
